#:schema node_modules/wrangler/config-schema.json
name = "ss-headless-cms-test"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "headless-cms-db"
database_id = "1db68836-5bab-4bf2-b8fa-67c7797ae52e"
